development:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    #database: WhatsTheNumber_Dev
    database: Smark
    pool: 5
    username: root
    password: "24479994"
    #socket: /var/run/mysqld/mysqld.sock
    socket: /tmp/mysql.sock

production:
    adapter: mysql2
    encoding: utf8
    reconnect: true
    host: grabit.c4kx7jpum9uh.ap-northeast-1.rds.amazonaws.com
    database: Smark
    pool: 2
    username: grab_it
    password: "zxcvbnm,"
    #socket: /var/run/mysqld/mysqld.sock
    #socket: /tmp/mysql.sock

